/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DAO.DiemDAO;
import DAO.LoaiDiemDAO;
import DAO.LopDAO;
import DAO.MonhocDAO;
import DAO.SinhVienDAO;
import Model.DSDiem;
import Model.Diem;
import Model.LoaiDiem;
import Model.Lop;
import Model.MonHoc;
import Model.SinhVien;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


public final class MainForm extends javax.swing.JFrame {

    LopDAO lopDAO = new LopDAO();
    MonhocDAO monDAO = new MonhocDAO();
    SinhVienDAO svDAO = new SinhVienDAO();
    DiemDAO diemDAO = new DiemDAO();
    LoaiDiemDAO ldDAO = new LoaiDiemDAO();
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        String tenDangNhap = System.getProperty("Admin");
        if (tenDangNhap == null) {
            LoginForm login = new LoginForm(this);
            login.setVisible(true);
        }
        reload();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        lblwelcome = new javax.swing.JLabel();
        pnlLop = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnThemlop = new javax.swing.JButton();
        btnSualop = new javax.swing.JButton();
        btnXoalop = new javax.swing.JButton();
        pnlDSLop = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSLop = new javax.swing.JTable();
        pnlMon = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnThemmon = new javax.swing.JButton();
        btnSuamon = new javax.swing.JButton();
        btnXoamon = new javax.swing.JButton();
        pnlDSMon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSMon = new javax.swing.JTable();
        pnlSV = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnThemSV = new javax.swing.JButton();
        btnSuaSV = new javax.swing.JButton();
        btnXoaSV = new javax.swing.JButton();
        pnlDSSV = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDSSV = new javax.swing.JTable();
        pnlDiem = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnThemdiem = new javax.swing.JButton();
        btnSuadiem = new javax.swing.JButton();
        btnXoadiem = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        pnlDSSV1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDSDiem = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnDangXuat = new javax.swing.JMenuItem();
        mnThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm");

        pnlSidebar.setMaximumSize(new java.awt.Dimension(30, 100));
        pnlSidebar.setMinimumSize(new java.awt.Dimension(30, 100));
        pnlSidebar.setLayout(new javax.swing.BoxLayout(pnlSidebar, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlSidebar.add(jButton1);

        jButton2.setText("Lớp");
        jButton2.setMaximumSize(new java.awt.Dimension(85, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(85, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(85, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlSidebar.add(jButton2);

        jButton3.setText("Môn");
        jButton3.setMaximumSize(new java.awt.Dimension(85, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(85, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlSidebar.add(jButton3);

        jButton4.setText("Sinh viên");
        jButton4.setMaximumSize(new java.awt.Dimension(85, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(85, 23));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnlSidebar.add(jButton4);

        jButton5.setText("Điểm");
        jButton5.setMaximumSize(new java.awt.Dimension(85, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(85, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnlSidebar.add(jButton5);

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.LINE_START);

        pnlContent.setLayout(new java.awt.CardLayout());

        lblwelcome.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblwelcome.setText("Welcome");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(lblwelcome)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblwelcome)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        pnlContent.add(pnlDashboard, "cardDashboard");

        pnlLop.setPreferredSize(new java.awt.Dimension(85, 23));
        pnlLop.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Danh sách lớp");

        btnThemlop.setText("Thêm");
        btnThemlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemlopActionPerformed(evt);
            }
        });

        btnSualop.setText("Sửa");
        btnSualop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSualopActionPerformed(evt);
            }
        });

        btnXoalop.setText("Xóa");
        btnXoalop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoalopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(256, 256, 256))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemlop, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSualop, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoalop, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemlop)
                    .addComponent(btnSualop)
                    .addComponent(btnXoalop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLop.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnlDSLop.setLayout(new javax.swing.BoxLayout(pnlDSLop, javax.swing.BoxLayout.LINE_AXIS));

        tblDSLop.setAutoCreateRowSorter(true);
        tblDSLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSLopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSLop);

        pnlDSLop.add(jScrollPane1);

        pnlLop.add(pnlDSLop, java.awt.BorderLayout.CENTER);

        pnlContent.add(pnlLop, "cardLop");

        pnlMon.setPreferredSize(new java.awt.Dimension(85, 23));
        pnlMon.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Danh sách môn học");

        btnThemmon.setText("Thêm");
        btnThemmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemmonActionPerformed(evt);
            }
        });

        btnSuamon.setText("Sửa");
        btnSuamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuamonActionPerformed(evt);
            }
        });

        btnXoamon.setText("Xóa");
        btnXoamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoamonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemmon, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuamon, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoamon, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(217, 217, 217))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemmon)
                    .addComponent(btnSuamon)
                    .addComponent(btnXoamon))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMon.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pnlDSMon.setLayout(new javax.swing.BoxLayout(pnlDSMon, javax.swing.BoxLayout.LINE_AXIS));

        tblDSMon.setAutoCreateRowSorter(true);
        tblDSMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSMonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDSMon);

        pnlDSMon.add(jScrollPane2);

        pnlMon.add(pnlDSMon, java.awt.BorderLayout.CENTER);

        pnlContent.add(pnlMon, "cardMon");

        pnlSV.setPreferredSize(new java.awt.Dimension(85, 23));
        pnlSV.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Danh sách sinh viên");

        btnThemSV.setText("Thêm");
        btnThemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSVActionPerformed(evt);
            }
        });

        btnSuaSV.setText("Sửa");
        btnSuaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSVActionPerformed(evt);
            }
        });

        btnXoaSV.setText("Xóa");
        btnXoaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemSV, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuaSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(204, 204, 204))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSV)
                    .addComponent(btnSuaSV)
                    .addComponent(btnXoaSV))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlSV.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pnlDSSV.setLayout(new javax.swing.BoxLayout(pnlDSSV, javax.swing.BoxLayout.LINE_AXIS));

        tblDSSV.setAutoCreateRowSorter(true);
        tblDSSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSSVMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDSSV);

        pnlDSSV.add(jScrollPane3);

        pnlSV.add(pnlDSSV, java.awt.BorderLayout.CENTER);

        pnlContent.add(pnlSV, "cardSV");

        pnlDiem.setPreferredSize(new java.awt.Dimension(85, 23));
        pnlDiem.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Danh sách điểm");

        btnThemdiem.setText("Thêm");
        btnThemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemdiemActionPerformed(evt);
            }
        });

        btnSuadiem.setText("Sửa");
        btnSuadiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuadiemActionPerformed(evt);
            }
        });

        btnXoadiem.setText("Xóa");
        btnXoadiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoadiemActionPerformed(evt);
            }
        });

        btnChiTiet.setText("Chi tiết");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuadiem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoadiem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(239, 239, 239))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemdiem)
                    .addComponent(btnSuadiem)
                    .addComponent(btnXoadiem)
                    .addComponent(btnChiTiet))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlDiem.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pnlDSSV1.setLayout(new javax.swing.BoxLayout(pnlDSSV1, javax.swing.BoxLayout.LINE_AXIS));

        tblDSDiem.setAutoCreateRowSorter(true);
        tblDSDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSDiemMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDSDiem);

        pnlDSSV1.add(jScrollPane4);

        pnlDiem.add(pnlDSSV1, java.awt.BorderLayout.CENTER);

        pnlContent.add(pnlDiem, "cardDiem");

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        mnDangXuat.setText("Đăng xuất");
        jMenu1.add(mnDangXuat);

        mnThoat.setText("Thoát");
        mnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnThoatActionPerformed(evt);
            }
        });
        jMenu1.add(mnThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void welcome(String ten){
        lblwelcome.setText("Welcome "+ ten);
    }
    
    public void reload(){
        loadDSlop();
        loadDSmon();
        loadDSSV();
        loadDSDiem();
        DisEn(false);
    }
    public void loadDSlop(){
        JTable table = new JTable();
        DefaultTableModel tbl = new DefaultTableModel();
        Object rows[] = new Object[2];
        Object cols[] = new Object[2];
        cols[0] = "Mã lớp";
        cols[1] = "Tên Lớp";
        
        tbl.setColumnIdentifiers(cols);
        
        List<Lop> listlop = lopDAO.getAll();
        
        for (int i = 0; i < listlop.size(); i++) {
            Lop l = listlop.get(i);
            rows[0] = l.getMaLop();
            rows[1] = l.getTenLop();
            
            tbl.addRow(rows);
        }
        //table.setModel(tbl);
        //TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblDSLop.getModel());
        //tblDSLop.setRowSorter(sorter);

        //List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        //sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        //sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        //sorter.setSortKeys(sortKeys);
        //JScrollPane pane =new JScrollPane(table);
        tblDSLop.setModel(tbl);
    }
    
    public void loadDSmon(){
        JTable table = new JTable();
        DefaultTableModel tbl = new DefaultTableModel();
        Object rows[] = new Object[2];
        Object cols[] = new Object[2];
        cols[0] = "Mã môn học";
        cols[1] = "Tên môn học";
        
        tbl.setColumnIdentifiers(cols);
        
        List<MonHoc> listmon = monDAO.getAll();
        
        for (int i = 0; i < listmon.size(); i++) {
            MonHoc m = listmon.get(i);
            rows[0] = m.getMaMH();
            rows[1] = m.getTenMH();
            
            tbl.addRow(rows);
        }
        tblDSMon.setModel(tbl);
    }
    
    public void loadDSSV(){
        JTable table = new JTable();
        DefaultTableModel tbl = new DefaultTableModel();
        Object rows[] = new Object[6];
        Object cols[] = new Object[6];
        cols[0] = "Mã sinh viên";
        cols[1] = "Tên sinh viên";
        cols[2] = "Ngày sinh";
        cols[3] = "Giới tính";
        cols[4] = "Địa chỉ";
        cols[5] = "Lớp";
        
        tbl.setColumnIdentifiers(cols);
        
        List<SinhVien> listSV = svDAO.getAll();
        List<Lop> listLop = lopDAO.getAll();
        for (int i = 0; i < listSV.size(); i++) {
            SinhVien sv = listSV.get(i);
            rows[0] = sv.getMaSV();
            rows[1] = sv.getTenSV();
            rows[2] = sv.getNgaysinh();
            if(sv.getGioitinh()==false)
                rows[3] = "Nam";
            else
                rows[3] = "Nữ";
            rows[4] = sv.getDiachi();
            for (int j = 0; j < listLop.size(); j++) {
                Lop l = listLop.get(j);
                if(sv.getMaLop()==l.getMaLop())
                rows[5] = l.getTenLop();
            }
            
            
            tbl.addRow(rows);
        }
        tblDSSV.setModel(tbl);
    }
    
    public void loadDSDiem(){
        JTable table = new JTable();
        DefaultTableModel tbl = new DefaultTableModel();
        Object rows[] = new Object[6];
        Object cols[] = new Object[6];
        cols[0] = "Mã sinh viên";
        cols[1] = "Tên sinh viên";
        cols[2] = "Lớp";
        cols[3] = "Môn";
        cols[4] = "Loại điểm";
        cols[5] = "Điểm";
               
        tbl.setColumnIdentifiers(cols);
        List<Diem> listDiem = diemDAO.getAll();
        List<SinhVien> listSV = svDAO.getAll();
        List<Lop> listLop = lopDAO.getAll();
        List<LoaiDiem> listLD = ldDAO.getAll();
        List<MonHoc> listMon = monDAO.getAll();
        List<DSDiem> listDSD = diemDAO.getAll1();
        for (int i = 0; i < listDiem.size(); i++) {
            DSDiem dsd = listDSD.get(i);
            
            
            rows[0] = dsd.getMaSV();
            rows[1] = dsd.getTenSV();
            rows[2] = dsd.getTenLop();
            rows[3] = dsd.getTenMH();
            rows[4] = dsd.getTenLoai();
            rows[5] = dsd.getDiem();
            
            tbl.addRow(rows);
        }
        tblDSDiem.setModel(tbl);
    }
    
    //<editor-fold defaultstate="collapsed" desc="CardLayout">
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cardLayout = (CardLayout)pnlContent.getLayout();
        cardLayout.show(pnlContent, "cardDashboard");
        reload();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout cardLayout = (CardLayout)pnlContent.getLayout();
        cardLayout.show(pnlContent, "cardLop");
        reload();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardLayout cardLayout = (CardLayout)pnlContent.getLayout();
        cardLayout.show(pnlContent, "cardMon");
        reload();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CardLayout cardLayout = (CardLayout)pnlContent.getLayout();
        cardLayout.show(pnlContent, "cardSV");
        reload();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout cardLayout = (CardLayout)pnlContent.getLayout();
        cardLayout.show(pnlContent, "cardDiem");
        reload();
    }//GEN-LAST:event_jButton5ActionPerformed
//</editor-fold>
    
    private void mnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnThoatActionPerformed
        String message = "Bạn có chắc chắn muốn thoát ?";
        String title = "Thoát";
        // display the JOptionPane showConfirmDialog
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_mnThoatActionPerformed

    private void DisEn(boolean e)
    {
        btnSualop.setEnabled(e);
        btnXoalop.setEnabled(e);
        btnSuamon.setEnabled(e);
        btnXoamon.setEnabled(e);
        btnSuaSV.setEnabled(e);
        btnXoaSV.setEnabled(e);
        btnSuadiem.setEnabled(e);
        btnXoadiem.setEnabled(e);
    }
    // <editor-fold defaultstate="collapsed" desc="Lop">
    private void btnSualopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSualopActionPerformed
        
        if(tblDSLop.getSelectedRowCount()==0)
            JOptionPane.showMessageDialog(pnlContent, "Mời chọn lại");
        else
        {
            int row = tblDSLop.getSelectedRow();
            int ma = (int) tblDSLop.getValueAt(row, 0);
            String name = tblDSLop.getValueAt(row, 1).toString();
            SuaLopDialog j = new SuaLopDialog(this, true,ma,name);
            j.setVisible(true);
            reload();
        }
    }//GEN-LAST:event_btnSualopActionPerformed

    private void btnThemlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemlopActionPerformed
        //FrmThemLop f = new FrmThemLop();
        //f.setVisible(true);
        
        ThemLopDialog j = new ThemLopDialog(this, true);
        j.setVisible(true);
        reload();
    }//GEN-LAST:event_btnThemlopActionPerformed

    private void btnXoalopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoalopActionPerformed
        int row = tblDSLop.getSelectedRow();
        String ma = tblDSLop.getValueAt(row, 0).toString();
        int i = JOptionPane.showConfirmDialog(pnlContent,"Bạn có chắc chắn muốn xóa ?","Xóa",JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION)
        {
            lopDAO.XoaLop(ma);
            JOptionPane.showMessageDialog(pnlContent, "Xóa thành công");
            loadDSlop();
        }
        
    }//GEN-LAST:event_btnXoalopActionPerformed
    
    private void tblDSLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSLopMouseClicked
        DisEn(true);
    }//GEN-LAST:event_tblDSLopMouseClicked
//</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Mon hoc">
    private void btnThemmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemmonActionPerformed
        ThemMonDialog d = new ThemMonDialog(this, true);
        d.setVisible(true);
        reload();
    }//GEN-LAST:event_btnThemmonActionPerformed

    
    private void btnSuamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuamonActionPerformed
        int row = tblDSMon.getSelectedRow();
            int ma = (int) tblDSMon.getValueAt(row, 0);
            String name = tblDSMon.getValueAt(row, 1).toString();
            SuaMonDialog j = new SuaMonDialog(this, true,ma,name);
            j.setVisible(true);
            reload();
    }//GEN-LAST:event_btnSuamonActionPerformed

    private void btnXoamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoamonActionPerformed
        int row = tblDSMon.getSelectedRow();
        String ma = tblDSMon.getValueAt(row, 0).toString();
        int i = JOptionPane.showConfirmDialog(pnlContent,"Bạn có chắc chắn muốn xóa ?","Xóa",JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION)
        {
            if(monDAO.XoaMon(ma))
                JOptionPane.showMessageDialog(pnlContent, "Xóa thành công");
            else
                JOptionPane.showMessageDialog(pnlContent, "Xóa thất bại");
            loadDSmon();
        }
    }//GEN-LAST:event_btnXoamonActionPerformed

    private void tblDSMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSMonMouseClicked
        DisEn(true);
    }//GEN-LAST:event_tblDSMonMouseClicked

    //</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Sinh vien">
    private void btnThemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSVActionPerformed
        ThemSVDialog d = new ThemSVDialog(this, true);
        d.setVisible(true);
        reload();
    }//GEN-LAST:event_btnThemSVActionPerformed

    private void btnSuaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSVActionPerformed
        if(tblDSSV.getSelectedRowCount()==0)
            JOptionPane.showMessageDialog(pnlContent, "Mời chọn lại");
        else
        {
            int row = tblDSSV.getSelectedRow();
            String ma = (String) tblDSSV.getValueAt(row, 0);
            SuaSVDialog j = new SuaSVDialog(this, true,ma);
            j.setVisible(true);
            reload();
        }
    }//GEN-LAST:event_btnSuaSVActionPerformed

    private void btnXoaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSVActionPerformed
        int row = tblDSSV.getSelectedRow();
        String ma = tblDSSV.getValueAt(row, 0).toString();
        int i = JOptionPane.showConfirmDialog(pnlContent,"Bạn có chắc chắn muốn xóa ?","Xóa",JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION)
        {
            if(svDAO.XoaSV(ma))
                JOptionPane.showMessageDialog(pnlContent, "Xóa thành công");
            else
                JOptionPane.showMessageDialog(pnlContent, "Xóa thất bại");
            loadDSSV();
        }
    }//GEN-LAST:event_btnXoaSVActionPerformed

    private void tblDSSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSSVMouseClicked
        DisEn(true);
    }//GEN-LAST:event_tblDSSVMouseClicked
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Diem">
    private void btnThemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemdiemActionPerformed
        ThemDiemDialog d = new ThemDiemDialog(this, true);
        d.setVisible(true);
        reload();
    }//GEN-LAST:event_btnThemdiemActionPerformed

    private void btnSuadiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuadiemActionPerformed
        int row = tblDSDiem.getSelectedRow();
        String ma = tblDSDiem.getValueAt(row, 0).toString();
        String tenmh = tblDSDiem.getValueAt(row, 3).toString();
        String tenld = tblDSDiem.getValueAt(row, 4).toString();
        SuaDiemDialog d = new SuaDiemDialog(this, true, ma,tenmh,tenld);
        d.setVisible(true);
        reload();
    }//GEN-LAST:event_btnSuadiemActionPerformed

    private void btnXoadiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoadiemActionPerformed
        int row = tblDSDiem.getSelectedRow();
        String ma = tblDSDiem.getValueAt(row, 0).toString();
        int mamh = 0,mald = 0;
        List<MonHoc> listmh = monDAO.getAll();
        for (int i = 0; i < listmh.size(); i++) {
            MonHoc mh = listmh.get(i);
            String tenmh = tblDSDiem.getValueAt(row, 3).toString();
            if(tenmh.equals(mh.getTenMH()))
                mamh = mh.getMaMH();       
        }
        
        List<LoaiDiem> listld = ldDAO.getAll();
        for (int j = 0; j < listld.size(); j++) {
            LoaiDiem ld = listld.get(j);
            String tenld = tblDSDiem.getValueAt(row, 4).toString();
            if(tenld.equals(ld.getTenLoai()))
                mald = ld.getMaLoai();
        }
        
        
        int i = JOptionPane.showConfirmDialog(pnlContent,"Bạn có chắc chắn muốn xóa ?","Xóa",JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION)
        {
            if(diemDAO.XoaDiem(ma,mamh,mald))
                JOptionPane.showMessageDialog(pnlContent, "Xóa thành công");
            else
                JOptionPane.showMessageDialog(pnlContent, "Xóa thất bại");
            
            loadDSDiem();
        }
    }//GEN-LAST:event_btnXoadiemActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        ChitietDialog d = new ChitietDialog(this, true);
        d.setVisible(true);
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void tblDSDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSDiemMouseClicked
        DisEn(true);
    }//GEN-LAST:event_tblDSDiemMouseClicked
    //</editor-fold>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnSuaSV;
    private javax.swing.JButton btnSuadiem;
    private javax.swing.JButton btnSualop;
    private javax.swing.JButton btnSuamon;
    private javax.swing.JButton btnThemSV;
    private javax.swing.JButton btnThemdiem;
    private javax.swing.JButton btnThemlop;
    private javax.swing.JButton btnThemmon;
    private javax.swing.JButton btnXoaSV;
    private javax.swing.JButton btnXoadiem;
    private javax.swing.JButton btnXoalop;
    private javax.swing.JButton btnXoamon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JMenuItem mnDangXuat;
    private javax.swing.JMenuItem mnThoat;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlDSLop;
    private javax.swing.JPanel pnlDSMon;
    private javax.swing.JPanel pnlDSSV;
    private javax.swing.JPanel pnlDSSV1;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlDiem;
    private javax.swing.JPanel pnlLop;
    private javax.swing.JPanel pnlMon;
    private javax.swing.JPanel pnlSV;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JTable tblDSDiem;
    private javax.swing.JTable tblDSLop;
    private javax.swing.JTable tblDSMon;
    private javax.swing.JTable tblDSSV;
    // End of variables declaration//GEN-END:variables
}
