/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DAO.DiemDAO;
import DAO.LoaiDiemDAO;
import DAO.LopDAO;
import DAO.MonhocDAO;
import DAO.SinhVienDAO;
import Model.Diem;
import Model.LoaiDiem;
import Model.Lop;
import Model.MonHoc;
import Model.SinhVien;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class ThemDiemDialog extends javax.swing.JDialog {
    LopDAO lopDAO = new LopDAO();
    SinhVienDAO svDAO = new SinhVienDAO();
    MonhocDAO monDAO = new MonhocDAO();
    LoaiDiemDAO ldDAO = new LoaiDiemDAO();
    DiemDAO diemDAO = new DiemDAO();
    List a = new ArrayList();
    List b = new ArrayList();
    /**
     * Creates new form themDiemDialog
     */
    public ThemDiemDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadDSSV();
        loadcboLoai();
        loadcboMon();
    }
    
        public void loadDSSV(){
        JTable table = new JTable();
        DefaultTableModel tbl = new DefaultTableModel();
        Object rows[] = new Object[6];
        Object cols[] = new Object[6];
        cols[0] = "Mã sinh viên";
        cols[1] = "Tên sinh viên";
        cols[2] = "Ngày sinh";
        cols[3] = "Giới tính";
        cols[4] = "Địa chỉ";
        cols[5] = "Lớp";
        
        tbl.setColumnIdentifiers(cols);
        
        List<SinhVien> listSV = svDAO.getAll();
        List<Lop> listLop = lopDAO.getAll();
        for (int i = 0; i < listSV.size(); i++) {
            SinhVien sv = listSV.get(i);
            rows[0] = sv.getMaSV();
            rows[1] = sv.getTenSV();
            rows[2] = sv.getNgaysinh();
            if(sv.getGioitinh()==false)
                rows[3] = "Nam";
            else
                rows[3] = "Nữ";
            rows[4] = sv.getDiachi();
            for (int j = 0; j < listLop.size(); j++) {
                Lop l = listLop.get(j);
                if(sv.getMaLop()==l.getMaLop())
                rows[5] = l.getTenLop();
            }
            
            
            tbl.addRow(rows);
        }
        tblDSSV.setModel(tbl);
    }
        
    private void loadcboMon(){
        List<MonHoc> listmon = monDAO.getAll();
        for (int i = 0; i < listmon.size(); i++) {
            MonHoc mh = listmon.get(i);
            a.add(i, mh.getMaMH());
            cboMon.addItem(mh.getTenMH());

        }
    }
    
    private void loadcboLoai(){
        List<LoaiDiem> listld = ldDAO.getAll();
        for (int i = 0; i < listld.size(); i++) {
            LoaiDiem ld = listld.get(i);
            b.add(i, ld.getMaLoai());
            cboLoai.addItem(ld.getTenLoai());

        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSSV = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboMon = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblDSSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDSSV);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Thêm điểm");

        jLabel2.setText("Môn học");

        jLabel3.setText("Loại điểm");

        jLabel4.setText("Điểm");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDiem, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboMon, javax.swing.GroupLayout.Alignment.TRAILING, 0, 56, Short.MAX_VALUE)
                                    .addComponent(cboLoai, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(36, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnHuy))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        Diem d = new Diem();
        if(tblDSSV.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, "Mời chọn lại");}
        else{
            int row = tblDSSV.getSelectedRow();
            String ma = tblDSSV.getValueAt(row, 0).toString();
            d.setMaSV(ma);
            d.setMaMH((int) a.get(cboMon.getSelectedIndex()));
            d.setMaLoai((int) b.get(cboLoai.getSelectedIndex()));
            d.setDiem(Integer.parseInt(txtDiem.getText()));
            if(txtDiem.toString()==""){
                JOptionPane.showMessageDialog(null, "Nhập lại điểm");
            }
            else{
                if(diemDAO.themMoi(d)){
                    JOptionPane.showMessageDialog(rootPane, "Thêm mới thành công");
                     }
                else
                    JOptionPane.showMessageDialog(rootPane, "Thêm mới thất bại");
                }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboMon;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSSV;
    private javax.swing.JTextField txtDiem;
    // End of variables declaration//GEN-END:variables
}
